import "./globals.css";
import type { ReactNode } from "react";

export const metadata = {
  title: "Akie Generated App",
  description: "Generated by Akie AI",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}        <script src="/akie-badge.js" defer data-akie-project="proj_2d399b95"></script>
      </body>
    </html>
  );
}
