import "./globals.css";
import type { ReactNode } from "react";

export const metadata = {
  title: "Akie Generated App",
  description: "Generated by Akie AI",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
